/**
 * PDF Export Service
 *
 * Generate PDF reports for M&E data
 * Uses browser's print API for PDF generation
 */

import type { ExcelReportData } from './excelExport';

/**
 * Generate PDF report from data
 *
 * @param title - Report title
 * @param data - Report data
 * @param metadata - Additional metadata
 */
export function generatePDFReport(
  title: string,
  data: ExcelReportData,
  metadata?: {
    generatedBy?: string;
    dateRange?: string;
    organizationName?: string;
  }
): void {
  // Create a new window for printing
  const printWindow = window.open('', '_blank');

  if (!printWindow) {
    alert('Please allow pop-ups to generate PDF reports');
    return;
  }

  // Generate HTML content
  const htmlContent = generatePDFHTML(title, data, metadata);

  // Write content to new window
  printWindow.document.write(htmlContent);
  printWindow.document.close();

  // Wait for content to load, then trigger print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
      // Close window after printing (user can cancel)
      printWindow.onafterprint = () => {
        printWindow.close();
      };
    }, 250);
  };
}

/**
 * Generate HTML content for PDF
 *
 * @param title - Report title
 * @param data - Report data
 * @param metadata - Additional metadata
 * @returns HTML string
 */
function generatePDFHTML(
  title: string,
  data: ExcelReportData,
  metadata?: {
    generatedBy?: string;
    dateRange?: string;
    organizationName?: string;
  }
): string {
  const now = new Date().toLocaleString('en-ZA', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      font-size: 10pt;
      line-height: 1.4;
      color: #000;
      padding: 20mm;
    }

    .header {
      margin-bottom: 20px;
      padding-bottom: 15px;
      border-bottom: 2px solid #000;
    }

    .header h1 {
      font-size: 18pt;
      font-weight: 700;
      margin-bottom: 10px;
      color: #000;
    }

    .metadata {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 10px;
      font-size: 9pt;
      color: #333;
      margin-bottom: 20px;
    }

    .metadata-item {
      display: flex;
      gap: 5px;
    }

    .metadata-label {
      font-weight: 600;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
      page-break-inside: auto;
    }

    thead {
      background-color: #f5f5f5;
    }

    th {
      padding: 8px 6px;
      text-align: left;
      font-weight: 600;
      font-size: 9pt;
      border-bottom: 2px solid #000;
      border-top: 1px solid #ddd;
    }

    td {
      padding: 6px;
      font-size: 9pt;
      border-bottom: 1px solid #e0e0e0;
    }

    tr {
      page-break-inside: avoid;
      page-break-after: auto;
    }

    tbody tr:nth-child(even) {
      background-color: #fafafa;
    }

    tbody tr:hover {
      background-color: #f0f0f0;
    }

    .footer {
      margin-top: 30px;
      padding-top: 15px;
      border-top: 1px solid #ddd;
      font-size: 8pt;
      color: #666;
      text-align: center;
    }

    .summary {
      margin-bottom: 20px;
      padding: 15px;
      background-color: #f9f9f9;
      border-left: 4px solid #0071e3;
    }

    .summary-title {
      font-weight: 600;
      margin-bottom: 8px;
      font-size: 11pt;
    }

    .summary-text {
      font-size: 9pt;
      color: #333;
    }

    @media print {
      body {
        padding: 15mm;
      }

      .no-print {
        display: none;
      }

      table {
        page-break-inside: auto;
      }

      tr {
        page-break-inside: avoid;
        page-break-after: auto;
      }

      thead {
        display: table-header-group;
      }

      tfoot {
        display: table-footer-group;
      }
    }

    @page {
      size: A4;
      margin: 15mm;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    ${metadata?.organizationName ? `<p style="font-size: 11pt; color: #666;">${metadata.organizationName}</p>` : ''}
  </div>

  <div class="metadata">
    <div class="metadata-item">
      <span class="metadata-label">Generated:</span>
      <span>${now}</span>
    </div>
    ${metadata?.generatedBy ? `
    <div class="metadata-item">
      <span class="metadata-label">Generated By:</span>
      <span>${metadata.generatedBy}</span>
    </div>
    ` : ''}
    ${metadata?.dateRange ? `
    <div class="metadata-item">
      <span class="metadata-label">Date Range:</span>
      <span>${metadata.dateRange}</span>
    </div>
    ` : ''}
    <div class="metadata-item">
      <span class="metadata-label">Total Records:</span>
      <span>${data.rows.length}</span>
    </div>
  </div>

  ${data.rows.length > 0 ? `
  <table>
    <thead>
      <tr>
        ${data.headers.map((header) => `<th>${header}</th>`).join('')}
      </tr>
    </thead>
    <tbody>
      ${data.rows.map((row) => `
        <tr>
          ${row.map((cell) => `<td>${cell !== null && cell !== undefined ? cell : '-'}</td>`).join('')}
        </tr>
      `).join('')}
    </tbody>
  </table>
  ` : `
  <div class="summary">
    <div class="summary-title">No Data</div>
    <div class="summary-text">No records found for the selected date range.</div>
  </div>
  `}

  <div class="footer">
    <p>YETOMO Digital Delivery & Governance Platform | Generated on ${now}</p>
    <p style="margin-top: 5px; font-size: 7pt;">This is a computer-generated report. For official use only.</p>
  </div>
</body>
</html>
  `;
}

/**
 * Generate summary statistics for PDF header
 *
 * @param data - Report data
 * @returns Summary statistics
 */
export function generateReportSummary(data: ExcelReportData): string {
  const totalRecords = data.rows.length;

  if (totalRecords === 0) {
    return 'No records found for the selected criteria.';
  }

  return `Total records: ${totalRecords}`;
}
