import { useState, useEffect } from 'react';
import { GlassCard as Card } from '@/components/ui/GlassCard';
import { Button } from '@/components/ui/Button';
import { Download, FileText } from 'lucide-react';
import { generateReferenceLetter, type ReferenceLetter } from '@/services/reporting/advancedReports';
import { db } from '@/utils/db';
import { useAuthStore } from '@/store/useAuthStore';

export function ReferenceLetterPage() {
  const { user } = useAuthStore();
  const [participants, setParticipants] = useState<any[]>([]);
  const [selectedParticipant, setSelectedParticipant] = useState('');
  const [signedByTitle, setSignedByTitle] = useState('Project Manager');
  const [letter, setLetter] = useState<ReferenceLetter | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    loadParticipants();
  }, []);

  const loadParticipants = async () => {
    const data = await db.participants.toArray();
    setParticipants(data);
  };

  const handleGenerate = async () => {
    if (!selectedParticipant || !user) return;

    setLoading(true);
    try {
      const letterData = await generateReferenceLetter(
        selectedParticipant,
        user.fullName || user.email,
        signedByTitle
      );
      setLetter(letterData);
    } catch (error) {
      console.error('Failed to generate letter:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-24">
      <div>
        <h1 className="text-24 font-bold">Reference Letter Generator</h1>
        <p className="text-gray-600 mt-4">Generate professional reference letters for participants</p>
      </div>

      <Card className="p-24">
        <div className="space-y-16">
          <div>
            <label className="block text-sm font-medium mb-8">Participant</label>
            <select
              value={selectedParticipant}
              onChange={(e) => setSelectedParticipant(e.target.value)}
              className="w-full px-12 py-8 border rounded-md"
            >
              <option value="">Select a participant</option>
              {participants.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.fullName} - {p.idNumber}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium mb-8">Your Title</label>
            <input
              type="text"
              value={signedByTitle}
              onChange={(e) => setSignedByTitle(e.target.value)}
              className="w-full px-12 py-8 border rounded-md"
              placeholder="e.g., Project Manager"
            />
          </div>

          <Button
            onClick={handleGenerate}
            disabled={!selectedParticipant || loading}
            className="w-full"
          >
            <FileText className="w-16 h-16 mr-8" />
            {loading ? 'Generating...' : 'Generate Reference Letter'}
          </Button>
        </div>
      </Card>

      {letter && (
        <Card className="p-32">
          <div className="flex justify-end mb-24">
            <Button size="sm" variant="secondary">
              <Download className="w-16 h-16 mr-8" />
              Download PDF
            </Button>
          </div>

          <div
            className="prose max-w-none"
            dangerouslySetInnerHTML={{ __html: letter.content }}
          />

          <div className="mt-32 pt-24 border-t">
            <div className="grid grid-cols-2 gap-24 text-sm">
              <div>
                <p className="text-gray-600">Generated By</p>
                <p className="font-medium">{letter.signedBy}</p>
                <p className="text-gray-600">{letter.signedByTitle}</p>
              </div>
              <div>
                <p className="text-gray-600">Date Issued</p>
                <p className="font-medium">{new Date(letter.issuedDate).toLocaleDateString()}</p>
              </div>
            </div>
          </div>
        </Card>
      )}
    </div>
  );
}
export default ReferenceLetterPage;
